import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
              @keyframes marquee-scroll { from { transform: translateX(0); } to { transform: translateX(-50%); } }
              .marquee { position: relative; overflow: hidden; mask-image: linear-gradient(to right, transparent, black 10%, black 90%, transparent); -webkit-mask-image: linear-gradient(to right, transparent, black 10%, black 90%, transparent); }
              .marquee__track { display: flex; align-items: center; gap: 3rem; width: max-content; padding-inline: 1rem; animation: marquee-scroll 30s linear infinite; }
              .marquee:hover .marquee__track { animation-play-state: paused; }
              @media (prefers-reduced-motion: reduce) { .marquee__track { animation: none; } }
            `,
          }}
        />
        <Script
          strategy="afterInteractive"
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
      </head>
      <body suppressHydrationWarning className="antialiased">
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  );
}
